UKHomeOffice/digital-evidence-archive-on-aws

- .github/workflows/main-merge-workflow.yml
- source/dea-ui/ui/src/common/labels.tsx
> add multiple env to github action pipeline

- .github/workflows/main-merge-workflow.yml
- source/dea-ui/ui/src/common/labels.tsx
> Deploy DEA to DEV TEST PROD

- .github/workflows/main-merge-workflow.yml
- source/common/config/dev.json
- source/common/config/prod.json
- source/common/config/test.json
- source/dea-ui/ui/src/common/labels.tsx
> fix github action workflow within DEA code

- .github/workflows/main-merge-workflow.yml
> fix github action workflow

- .github/workflows/standalone.yml
- source/common/config/sandbox.json
Add a new workflow to test DEA deployment in Sandbox.
> Add a standalone workflow to deploy to Sandbox

- .github/workflows/main-merge-workflow.yml
> deploy latest DEA version1.0.5 to DEV env

- source/common/config/dev.json
- source/common/config/sandbox.json
- source/dea-backend/src/constructs/dea-rest-api.ts
Implementing a fix suggested by the product team at AWS to try and work around an issue where uploads time out after 1 hour.
> Increase maxSessionDuration for datasets role

- source/dea-backend/src/constructs/dea-auth.ts
update cognito password validity to 3 days.
> update pwd validity to 3 days

- source/common/config/dev.json
- source/dea-backend/src/config.ts
- source/dea-backend/src/constructs/dea-auth.ts
Attempt to fix issue where wrong AWS account Id appears in pre generate token role policy.
> Update policy for IdP.

- source/common/config/test.json
Add DEA test config to add Identity Center
> update dea test config to add identity center

- source/dea-ui/ui/src/common/labels.tsx
> update DEA banner

- source/dea-backend/src/constructs/dea-rest-api.ts
> revert maxSessionDuration

- source/dea-backend/src/constructs/dea-auth.ts
increase activation link from 1 to 3 days.
> increase duration from 1 to 7 for activation link

- source/dea-backend/src/constructs/dea-auth.ts
Restore welcome email message which seems to have drifted in Dev and Test.
> Fix DEA invitation email message

- source/dea-backend/src/constructs/dea-auth.ts
Remove duplicate https in welcome email text.
> Fix-welcome-message

- source/dea-backend/src/constructs/dea-backend-stack.ts
Add configuration for intelligent tiering to DEA Dataset bucket.
> Add intelligent tiering

- source/dea-backend/src/constructs/create-cloudwatch-to-athena-infra.ts
- source/dea-backend/src/constructs/dea-audit-trail.ts
- source/dea-main/src/dea-main-stack.ts
- source/dea-ui/infrastructure/src/dea-ui-stack.ts
Addressing issues raised by security report around bucket versioning and server logging of DEA buckets
> Enable versioning and server logging of DEA buckets.

- source/dea-backend/src/constructs/dea-backend-stack.ts
- source/dea-ui/infrastructure/src/dea-ui-stack.ts
Addressing security review findings to set the KMS key to a Customer Managed Key for the artifact and access log buckets.
> Enable KMS encryption with CMK

- source/dea-ui/infrastructure/src/dea-ui-stack.ts
CloudFormation stack failing on custom resource. Reverting all changes made to the artifact bucket.
> Revert changes to DEA UI artifact bucket

- source/dea-backend/src/constructs/create-cloudwatch-to-athena-infra.ts
Ensure that CMK is used to encrypt SQS messages.
> Encrypt SQS queues using CMK.

- source/dea-backend/src/constructs/create-cloudwatch-to-athena-infra.ts
Unused import causing build to fail.
> Remove unused import

- source/dea-backend/src/constructs/create-cloudwatch-to-athena-infra.ts
Build fails with circular dependency error when these changes were applied. Reverting the commits.
> Revert commits that broke the build.

- source/dea-backend/src/constructs/create-cloudwatch-to-athena-infra.ts
Addressing issue raised by Security Report
> Enforce SSL on SQS queues

- source/dea-backend/src/constructs/dea-rest-api.ts
Fixing recommendation made by security review.
> Enable rest api logging to cloudwatch.

- source/dea-backend/src/constructs/dea-rest-api.ts
Enable X-Ray tracing as per the security report recommendation.
> Enable tracing on rest api.

- source/dea-backend/src/constructs/dea-rest-api.ts
Attempt to fix the logging on DEA Rest API
> Change rest api logging settings.

- source/dea-backend/src/constructs/dea-rest-api.ts
Attempt to resolve drift in cloudformation stack.
> Remove traceEnabled at deploy level

- source/common/config/test.json
update test config to add vaults.
> update test.json to add vaults

- source/common/config/dev.json
Add the IdP config for the Entra Id metadata.xml to the DEA-Dev environment.
> Add Entra Id Idp config to Dev.

- source/dea-ui/ui/src/components/buttons/DownloadButton.tsx
Attempt to stop page blinking when multiple files are downloaded.
> Attempt to keep window focus.

- source/dea-ui/ui/src/components/upload-files/UploadFilesForm.tsx
Debugging issue during smoke test.
> Adding some debugging logs.

- source/dea-ui/ui/src/components/upload-files/UploadFilesForm.tsx
Reverting previous commits to add debug logging.
> Remove debug logging.

- source/common/config/dev.json
Add group to role mappings into the DEA config.
> Map Azure AD groups to DEA roles.

- source/common/config/dev.json
- source/dea-app/src/app/event-handlers/pretoken-generation-trigger.ts
Add groups claim into DEA IdP config.
Add some debug logging to see what groups are being found.
> Add groups claim to idpConfig attributeMap
